revert temp test changes

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -8,6 +8,122 @@
 
 kind: pipeline
 type: docker
+name: unit
+
+clone:
+  disable: true
+
+services:
+  - name: ci-tests-redis
+    image: redis
+    ports:
+      - 6379
+
+steps:
+  - name: bin/drone/shell
+    image: curlimages/curl
+    commands:
+      - set +x
+      # If running on EC2, get hostname from ec2 metadata
+      - "IMDS_TOKEN=$(curl -s -X PUT http://169.254.169.254/latest/api/token -H \"X-aws-ec2-metadata-token-ttl-seconds: 21600\")"
+      - "hostname=$(curl -s -H \"X-aws-ec2-metadata-token: $IMDS_TOKEN\" http://169.254.169.254/latest/meta-data/public-hostname)"
+      - |
+        cat <<EOF
+
+        Running on hostname: $hostname
+
+        To "ssh" into this drone instance, wait until the 'unit-tests' step starts and run:
+        bin/drone/shell $hostname
+
+        You can also open a VSCode tunnel into drone to edit live:
+        bin/drone/vscode $hostname
+        EOF
+
+  # Restore the staging build we created in the `cache-staging-build` pipeline
+  - name: get-cached-staging-build
+    image: plugins/s3-cache
+    settings:
+      filename: cache-staging-ci-build.tar.gz
+      endpoint: s3://cdo-drone
+      restore: true
+      debug: true
+      pull: true
+
+  - name: checkout
+    image: bitnamilegacy/git
+    environment:
+      GITHUB_TOKEN:
+        from_secret: GITHUB_TOKEN
+    commands:
+      - git lfs install --skip-repo
+      # Construct authenticated GitHub URL.
+      # DRONE_REPO_OWNER = organization name (e.g., "code-dot-org")
+      # DRONE_REPO_NAME = repository name (e.g., "code-dot-org")
+      - AUTHENTICATED_GITHUB_URL="https://$GITHUB_TOKEN@github.com/$DRONE_REPO_OWNER/$DRONE_REPO_NAME.git"
+      # Validate cache restore, since the restore step will pass even if it only downloaded a
+      # partial copy of the cached build. First, ensure the .git directory is present and valid.
+      - "git rev-parse --git-dir >/dev/null 2>&1 || { echo 'ERROR: Cache restore failed: .git dir is missing or invalid'; exit 1; }"
+      # Then, count the number of files outside of the .git directory and compare to how many were
+      # present in the cache. This is not a perfect check, but is much cheaper than computing a
+      # checksum of all files and is likely to catch most instances of incomplete downloads.
+      - |
+        if [ -f .cached-staging-build-file-count ]; then
+          expected=$(cat .cached-staging-build-file-count)
+          actual=$(find . -type f -not -path './.git/*' | wc -l)
+          diff=$((actual - expected))
+          [ "$expected" = "$actual" ] || printf 'WARN: File count mismatch. Expected: %s Actual: %s Diff: %s\n' "$expected" "$actual" "$diff"
+        fi
+      # Update the remote URL to use authentication
+      - git remote set-url origin $AUTHENTICATED_GITHUB_URL
+      # Checkout our source branch (=the PR)
+      - git fetch origin $DRONE_SOURCE_BRANCH
+      - git checkout $DRONE_SOURCE_BRANCH
+      - git pull
+      - git reset --hard $DRONE_COMMIT
+      # Fetch the target branch (which is staging for pull requests.) We need this for determining which tests to run based on changed files.
+      - git remote set-branches --add origin $DRONE_TARGET_BRANCH
+      - git fetch --depth 100 origin $DRONE_TARGET_BRANCH
+      # Merge so we're up-to-date with the target before running tests.
+      - git config user.name "Drone"
+      - git config user.email "drone-fake-user@code.org"
+      - git merge origin/$DRONE_TARGET_BRANCH
+
+  - name: unit-tests
+    # see: docker/ci/Dockerfile
+    image: codedotorg/cdo-ci:1.18
+    pull: always
+    environment:
+      CI_JOB: 'unit_tests'
+      # Each Drone secret below must be explicitly written to locals.yml in /docker/ci/scripts/prepare_ci_env.sh
+      CLOUDFRONT_KEY_PAIR_ID:
+        from_secret: CLOUDFRONT_KEY_PAIR_ID
+      CLOUDFRONT_PRIVATE_KEY:
+        from_secret: CLOUDFRONT_PRIVATE_KEY
+      CONTENTFUL_CS_FOR_ALL_ACCESS_TOKEN:
+        from_secret: CONTENTFUL_CS_FOR_ALL_ACCESS_TOKEN
+    commands:
+      # Cached data gets restored by the root user, so we need to reassign
+      - sudo chown -R ci:ci .
+      # Depended on by CI: https://github.com/code-dot-org/code-dot-org/blob/048e4ddffd52e62fd6a13566ea6ccd38a6701d89/lib/cdo/ci.rb/#L16
+      - export GIT_COMMIT=$DRONE_COMMIT
+      - export CI_BASE_BRANCH=$DRONE_TARGET_BRANCH
+      - export CI_HEAD_BRANCH=$DRONE_SOURCE_BRANCH
+      - EXIT_CODE=0
+      - /entrypoint.sh docker/ci/scripts/unit_tests.sh || EXIT_CODE=$?
+      - while pgrep bash >/dev/null; do echo "found bash process; keeping container alive"; sleep 20; done
+      - exit $EXIT_CODE
+
+trigger:
+  branch:
+    exclude:
+      - "production"
+      - "levelbuilder"
+  event:
+    - pull_request
+
+---
+kind: pipeline
+type: docker
 name: ui
 
 clone:
@@ -89,6 +205,10 @@ steps:
       # need this for determining which tests to run based on changed files.
       - git remote set-branches --add origin $DRONE_TARGET_BRANCH
       - git fetch --depth 100 origin $DRONE_TARGET_BRANCH
+      # Merge so we're up-to-date with the target before running tests.
+      - git config user.name "Drone"
+      - git config user.email "drone-fake-user@code.org"
+      - git merge origin/$DRONE_TARGET_BRANCH
 
   - name: ui-tests
     # see: docker/ci/Dockerfile
